# Generated by Django 3.2.4 on 2021-06-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=15, verbose_name='RUT Paciente')),
                ('Nombres', models.CharField(max_length=250, verbose_name='Nombres del Paciente')),
                ('Apellidos', models.CharField(max_length=250, verbose_name='Apellidos del Paciente')),
                ('Fecha_reserva', models.CharField(max_length=300, verbose_name='Fecha Reserva')),
                ('Hora_reserva', models.CharField(max_length=300, verbose_name='Hora Reserva')),
                ('correo', models.CharField(max_length=300, verbose_name='Email Paciente')),
                ('especialidad', models.CharField(max_length=300, verbose_name='Especialidad')),
                ('motivo_consulta', models.CharField(max_length=300, verbose_name='Motivo Consulta')),
                ('Medico_asignado', models.CharField(default='Sin Asignar', max_length=300, verbose_name='Medico ')),
            ],
        ),
    ]
