# Generated by Django 3.2.4 on 2021-06-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostaRuralApp', '0002_reservahora_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('user_type', models.CharField(default='Medico', max_length=300)),
                ('account_balance', models.CharField(default='0', max_length=50)),
                ('state_account', models.BooleanField(default=True)),
                ('RUT', models.CharField(max_length=13, unique=True, verbose_name='RUT')),
                ('admin_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'RUT',
            },
        ),
    ]
