# Generated by Django 3.2.4 on 2021-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostaRuralApp', '0003_usersalud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersalud',
            name='account_balance',
        ),
        migrations.AddField(
            model_name='usersalud',
            name='numero_telefono',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
