# Generated by Django 3.2.4 on 2021-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostaRuralApp', '0004_auto_20210619_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalud',
            name='user_type',
            field=models.CharField(default='Medico', max_length=300, verbose_name='Tipo usuario(Medico,Paciente,Administrador)'),
        ),
    ]
