# Generated by Django 3.2.4 on 2021-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostaRuralApp', '0005_alter_usersalud_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=15, verbose_name='RUT Paciente')),
                ('Nombres', models.CharField(max_length=250, verbose_name='Nombres del Paciente')),
                ('Apellidos', models.CharField(max_length=250, verbose_name='Apellidos del Paciente')),
                ('Genero', models.CharField(max_length=250, verbose_name='genero del Paciente')),
                ('celular', models.CharField(default='Sin Celular', max_length=300, verbose_name='Celular')),
                ('estado_civil', models.CharField(default='Soltero', max_length=300, verbose_name='estado civil')),
                ('comuna', models.CharField(max_length=250, verbose_name='comuna del Paciente')),
                ('region', models.CharField(max_length=250, verbose_name='region del Paciente')),
                ('direccion', models.CharField(max_length=250, verbose_name='direccion del Paciente')),
                ('nacimiento', models.CharField(max_length=250, verbose_name='fecha nacimiento del Paciente')),
                ('nacionalidad', models.CharField(max_length=250, verbose_name='nacionalidad del Paciente')),
                ('correo', models.CharField(max_length=250, verbose_name='correo del Paciente')),
                ('EnfermedadesCronicas', models.CharField(default='Sin Enfermedades', max_length=250, verbose_name='enfermedades cronicas del Paciente')),
                ('Alergias', models.CharField(default='Sin Alergias', max_length=250, verbose_name='alergias del Paciente')),
                ('AcompañanteNombre', models.CharField(max_length=250, verbose_name='nombre  del acompañante')),
                ('AcompañanteApellido', models.CharField(max_length=250, verbose_name='apellido  del acompañante')),
                ('RelacionAcompañante', models.CharField(max_length=250, verbose_name='relacion con el Paciente')),
                ('celularAcompañante', models.CharField(max_length=250, verbose_name='celular  del acompañante del paciente')),
            ],
        ),
    ]
